### ISSUE TITLE
macOS: Default is Cmd+Shift+Space, and Cmd+Shift+S conflicts

### ISSUE THREAD

**Issue by Jonta** [Claymont/detach-tab#2]
The former isn't mentioned, the latter brings up FF screenshot.

Ctrl+Shift+S seems to do nothing

**Comment by Claymont** [comment]
I have the screenshot feature disabled which is why I accidentally used the same keyboard shortcut that screenshot use [_Ctrl+Shift+S_].

I intend to fix this as soon as I get time some for it, hopefully soon.

---

Ctrl is translated to Cmd on Mac, MacCtrl is needed for it to be Ctrl on Macs [source](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands).

I've updated the description on the extensions AMO page.

I don't have a Mac so I don't know which would be preferable? Cmd or Ctrl?

**Comment by Jonta** [comment]
Cmd. =)

**Comment by Claymont** [comment]
Version 2.0.4 fixes the conflict.
